POST http://localhost:9999/api/client/0
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYxNjI1Njl9.Eea2ixx_2_91S42sbR_GNkzpKm4vnnSeE52hV9-7Uk7dwuLnvvYym_5Fzz8uNzvhPBEpmhq3AN1OtbEwaFRi9Q

{
  "first_name": "TestName",
  "last_name": "TestSurName",
  "middle_name": "",
  "login": "TestLogin22",
  "password": "TestPassword",
  "e_mail": "",
  "avatar": "",
  "phone": "999999"
}

###

POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login": "TestLogin2",
  "pass": "admin"
}

###

POST http://localhost:9999/api/client/password
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYxNjI1Njl9.Eea2ixx_2_91S42sbR_GNkzpKm4vnnSeE52hV9-7Uk7dwuLnvvYym_5Fzz8uNzvhPBEpmhq3AN1OtbEwaFRi9Q

{
  "id": 70,
  "old_pass": "TestPassword",
  "new_pass": "admin"
}

###

POST http://localhost:9999/api/client/avatar
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYxNjI1Njl9.Eea2ixx_2_91S42sbR_GNkzpKm4vnnSeE52hV9-7Uk7dwuLnvvYym_5Fzz8uNzvhPBEpmhq3AN1OtbEwaFRi9Q

{
  "id": 70,
  "avatar_url": "70"
}

###

POST http://localhost:9999/api/client/edit
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYxNjI1Njl9.Eea2ixx_2_91S42sbR_GNkzpKm4vnnSeE52hV9-7Uk7dwuLnvvYym_5Fzz8uNzvhPBEpmhq3AN1OtbEwaFRi9Q

{
  "id": 70,
  "first_name": "70",
  "last_name": "70",
  "middle_name": "70",
  "e_mail": ""
}

###

GET http://localhost:9999/api/status

###