POST http://localhost:9999/api/client/0
Content-Type: application/json

{
  "first_name": "TestName",
  "last_name": "TestSurName",
  "middle_name": "",
  "login": "TestLogin2",
  "password": "TestPassword",
  "e_mail": "",
  "avatar": "",
  "phone": "99999"
}

###

POST http://localhost:9999/api/token
Content-Type: application/json

{
  "login": "admin",
  "pass": "admin"
}

###

POST http://localhost:9999/api/client/password
Content-Type: application/json

{
  "id": 1,
  "old_pass": "admin",
  "new_pass": "qasw"
}

###

POST http://localhost:9999/api/client/avatar
Content-Type: application/json

{
  "id": 2,
  "avatar_url": "159"
}

###

POST http://localhost:9999/api/client/edit
Content-Type: application/json

{
  "id": 70,
  "first_name": "512",
  "last_name": "last",
  "middle_name": "6512",
  "e_mail": ""
}

###